proxy:
  port: 8080
  authentication: simple
  admin-groups: admins
  users:
  - name: jack
    password: password
    groups: admins
  - name: jeff
    password: password
  docker:
      internal-networking: true
  specs:
  - id: euler
    display-name: Euler's number
    container-cmd: ["R", "-e", "shiny::runApp('/root/euler')"]
    container-image: openanalytics/shinyproxy-template
    container-network: sp-example-net
  - id: eruption
    display-name: Eruption Histogram
    container-cmd: ["R", "-e", "shiny::runApp('/root/eruption')"]
    container-image: eruption_image
    container-network: sp-example-net

logging:
  file:
    shinyproxy.log